name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@297dbbf
        with:
          node-version: 20
      - uses: actions/upload-artifact@469fdae6c9a7a133f770f31f7ebfe863a834fba1  # v4.1.0
        with:
          name: build
          path: dist/
      - uses: actions/cache@145d7281d851cb2f0e335d9b256d80c13f353f7f
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - run: npm test
